### PR TITLE
Added Thai language

### PR DESCRIPTION
**Pull request by PJzuza**
Finally. I have done this one... The hardest one (I have to improvise a lot on data killtexts part :P)
```
- Added Thai language.
- Triggered Thai language by checking a mod's name.
```
Let me know if I should change or fix something and I've [tested](http://steamcommunity.com/sharedfiles/filedetails/?id=1339368408) before giving it to you as usual of course :)

And oh emm. You may have to fix some indents again. Sorry about that. I just saw it after I've made a PR.

### CODE REVIEW

**Comment by segabl** [comment]
No worries. I think you could work with BLT.Mods:GetMod( id ) in the future though to check if the thai mod is installed. saves you from adding that loop every time

**Comment by PJzuza** [comment]
@segabl True. Will try to find a way again then. Or maybe making another option to choose each language individually? Just like nepgeaesy main menu mod etc. That way works too.

**Comment by segabl** [comment]
It would be something like
```lua
local mod_language = PD2KR and "korean" or BLT.Mods:GetMod("mod_id") and "thai"
```
then which would simplify the code and I can keep everything in place neatly :)

**Comment by PJzuza** [comment]
Understood. Next mod that I will translate if that one is one of your mods. I'll make it better. And thanks for fast reply as usual :D

**Pull request merged**
